name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'    
  pull_request:
    branches: [ main ]

jobs:
  CheckSkipCI:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.pull_request.title, '[skip-ci]')
    steps:
      - run: exit 0

  build:
    runs-on: windows-latest
    needs: [CheckSkipCI]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Pack
      run: dotnet pack src --configuration Release --output build/packages

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Packages
        path: build/packages

    - name: Publish to NuGet
      shell: bash
      if: github.event_name == 'push'
      run: dotnet nuget push build/packages/**/*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}} true
